#kics-scan disable=baee238e-1921-4801-9c3f-79ae1d7b2cbc
name: Backend Build & Deploy

on:
  push:
    # Only run this workflow if changes are made to the backend code or the workflow file
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

# Permissions required for the workflow to run
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
    AWS_REGION: us-east-1
    IMAGE_TAG: ${{ github.run_number }}  # Use the GitHub Tag as the image tag
    ECR_REPO: ${{ secrets.ECR_REPO }}  # ECR repository URL

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to ECR
        run: |
          cd backend
          docker build -t ${{ env.ECR_REPO }}:v${{ env.IMAGE_TAG }} .
          docker push ${{ env.ECR_REPO }}:v${{ env.IMAGE_TAG }}
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7 # Specify the Terraform version to use
      - name: Terraform Init, Plan, and Apply
        run: |
          cd infra
          terraform validate
          terraform init
          terraform plan -target=aws_ecs_task_definition.backend -target=aws_ecs_service.backend -var="image_tag=v${{ env.IMAGE_TAG }}" -out=tfplan
          terraform apply -target=aws_ecs_task_definition.backend -target=aws_ecs_service.backend -auto-approve